spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: jungle-royale-redis-cache-ro.bgoupc.ng.0001.apn2.cache.amazonaws.com
      port: 6379
redisson:
  address: redis://jungle-royale-redis-cache-ro.bgoupc.ng.0001.apn2.cache.amazonaws.com:6379

kakao:
  client-id: e8304b2a6b5aeb5020ef6abeb405115b
  redirect-uri: http://eternalsnowman.com/login


base:
  url:
    item: "http://web-api.eternalsnowman.com:8080/uploads/items/"
    post: "http://web-api.eternalsnowman.com:8080/uploads/"