spring:
  application:
    name: jungleroyale
  profiles:
    active: dev # 기본 프로파일
  datasource:
    url: jdbc:mysql://jungle-royale-database.c9ok8ooiumgq.ap-northeast-2.rds.amazonaws.com:3306/jungleroyale
    username: admin
    password: jungleroyale2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000 # 29분

## 비밀키 생성 방법 : io.jsonwebtoken.security.Keys.secretKeyFor() 사용하여 HS512에 맞는 키 생성
jwt:
  secret-key: j5ZeFFn6lVIEnpuLFNa8aao/nLy1ZRLFppPB98cBvowj8RDNepK+Swe33cHLOVWeM7VZkb2HqCdU2CBOk11b4A==

logging:
  level:
    org.springframework.web: DEBUG

security:
  encryption:
    secret-key: "jungleroyale1234" # 16바이트 길이의 AES 키

upload:
  dir:
    item: "src/main/resources/static/uploads/items"
    post: "src/main/resources/static/uploads"

secret:
  hash:
    key: "jungleroyale"

springdoc:
  swagger-ui:
    # swagger-ui 접근 경로. default 값은 /swagger-ui.html이다.
    path: /swagger.html
    # 각 API의 그룹 표시 순서
    # path, query, body, response 순으로 출력
    groups-order: DESC
    # 태그 정렬 순서.
    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha

    # 컨트롤러 정렬 순서.
    # method는 delete - get - patch - post - put 순으로 정렬된다.
    # alpha를 사용해 알파벳 순으로 정렬할 수 있다.
    operations-sorter: method

    # swagger-ui default url인 petstore html의 비활성화 설정
    disable-swagger-default-url: true

    # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
    display-request-duration: true
    # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
    api-docs:
      path: /api-docs

    # Spring Actuator의 endpoint까지 보여줄 것인지?
    show-actuator: true

    # request media type 의 기본 값
    default-consumes-media-type: application/json

    # response media type 의 기본 값
    default-produces-media-type: application/json

    # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
    paths-to-match:
      - /api/**