spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

base:
  url:
    item: "http://192.168.1.241:8080/uploads/items/"
    post: "http://192.168.1.241:8080/uploads/posts/"
    shop: "http://192.168.1.241:8080/uploads/items/"

kakao:
#  client-id: 9b5e1f47241e82beb559d44bd2a25377  # 백엔드 서버
  client-id: e8304b2a6b5aeb5020ef6abeb405115b # 프론트엔드 서버

#  redirect-uri: http://192.168.1.241:8080/api/auth/kakao/callback  # 백엔드 개발 서버
  redirect-uri: http://localhost:5173/login # 프론트엔드 개발 서버
